version: 2
updates:
  # Maven dependencies
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "automated"
    commit-message:
      prefix: "build(deps)"
      include: "scope"
    ignore:
      # For more complex ignore patterns, you can add specific dependencies here
      # For example:
      # - dependency-name: "com.microsoft.playwright:playwright"
      #   versions: ["< 1.0.0"]

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "automated"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"